<?php

    /**
     * GetBD module configuration.
     *
     * This file is REGENERATED by the module after every settings save
     * (GetBD::controller_settings()), because WiseCP's own settings save
     * would otherwise replace it with a static export that leaks the
     * verification fields into the checkout. Edit config.template.php /
     * doc-fields.php instead — never hand-edit this file.
     */

    $getbd_settings = [
        'whois-types' => true,
        'api-key'     => '',
    ];

    return require __DIR__ . DS . 'config.template.php';
